server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: #路由数组
      - id: product_route #当前路由的标识，要求唯一
        #uri: http://localhost:8081  #请求要转发到的地址
        uri: lb://service-product # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略
        order: 1 #路由的优先级，数字越小级别越高
        predicates: #断言（路由转发要满足的条件）
          - Path=/product-serv/**  # 当请求路径满足Path指定的规则时，才进行路由转发
        filters: #过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
          - StripPrefix=1 #转发之前去掉1层路径
      - id: order_route #当前路由的标识，要求唯一
          #uri: http://localhost:8081  #请求要转发到的地址
        uri: lb://service-order # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略
        order: 1 #路由的优先级，数字越小级别越高
        predicates: #断言（路由转发要满足的条件）
          - Path=/order-serv/**  # 当请求路径满足Path指定的规则时，才进行路由转发
        filters: #过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
          - StripPrefix=1 #转发之前去掉1层路径
      enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discovery-client-enabled: false  #让nacos把他当作一个URL，而不要当作服务名
    sleuth:
      sampler:
        probability: 1.0 #采样的百分比

