server:
  port: 8091

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999
        dashboard: localhost:8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyh.entities    #所有Entity所在类别名包
  #开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
